version: '3.5'

services:

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    network_mode: host
    volumes:
      - /tmp/docker/diesel/mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER:     test
      MYSQL_PASSWORD: test
